title: Jaykumar Savani # your name (or website title) here
logo: "/images/linkedin.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  I am a Data Scientist with 2.5+ years of industrial experience and loves using ML techniques to retrieve valuable information from data and generate predictive models for future insights.
  <br><br>
  <a href="https://www.linkedin.com/in/jaykumarsavani1/">View My LinkedIn Profile</a> 
  <br>
  <a href="https://github.com/jaysavani1/">View My Github Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

colors:
  crimson: '#900C3F'
